CREATE CONSTRAINT node_agent_name IF NOT EXISTS FOR (n:Agent) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_domain_name IF NOT EXISTS FOR (n:Domain) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_hub_name IF NOT EXISTS FOR (n:Hub) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_kbentry_name IF NOT EXISTS FOR (n:KbEntry) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_skill_name IF NOT EXISTS FOR (n:Skill) REQUIRE n.name IS UNIQUE;
MERGE (n:Agent {name: 'build-release-specialist'}) SET n.role = 'vcs', n.description = 'Empacotar o app Node/TypeScript num executÃ¡vel Windows Ãºnico, publicar via GitHub Releases pelo Actions e manter a landing no GitHub Pages. Acione ao mexer em build, tamanho do binÃ¡rio, workflow de release ou no bootstrap de dependÃªncias do 1Âº uso.';
MERGE (n:Agent {name: 'code-reviewer'}) SET n.role = 'review', n.description = 'Revisor sÃªnior de diff/PR. Prioriza por risco (correÃ§Ã£o, concorrÃªncia, recursos, contrato/retrocompat, performance), lÃª o contexto e os chamadores alÃ©m do diff, revisa o que ficou de fora e casa a linguagem com a severidade â€” sinal alto, sem nit-bombing. Delega estilo aos linters de CI e profundidade de seguranÃ§a ao security-reviewer. Read-only.';
MERGE (n:Agent {name: 'debugger'}) SET n.role = 'debug', n.description = 'Vai da falha Ã  causa-raiz pelo mÃ©todo cientÃ­fico (hipÃ³teseâ†’prediÃ§Ã£oâ†’experimentoâ†’observaÃ§Ã£o), nÃ£o ao sintoma. Reproduz primeiro, checa ambiente antes da lÃ³gica, reduz o reprodutor (delta debugging), instrumenta com logs/traces, usa debugger e git bisect para regressÃ£o, e trata heisenbug/flaky/concorrÃªncia. Use quando algo quebra ou um teste falha sem causa Ã³bvia.';
MERGE (n:Agent {name: 'designer'}) SET n.role = 'design', n.description = 'Expert em UI/frontend que conduz shapeâ†’craftâ†’audit â€” contraste WCAG/APCA, design tokens (primitivoÃ—semÃ¢ntico), tipografia/espaÃ§o fluido, ARIA APG, Core Web Vitals (CLS/LCP/INP), motion com prefers-reduced-motion, anti-slop, static-first. Use ao criar/revisar/refinar interface. Aponta para a skill `impeccable` quando instalada (`/supplements design`); sem ela, aplica a mesma disciplina diretamente. NÃ£o carrega paleta/referÃªncias fixas de nenhum projeto.';
MERGE (n:Agent {name: 'documenter'}) SET n.role = 'documentation', n.description = 'Expert em escrita tÃ©cnica humanoÃ—LLM (fora da KB) â€” organiza `docs/` por DiÃ¡taxis (tutorial/how-to/reference/explanation), lavra ADR (Nygard/MADR), changelog Keep a Changelog derivado de Conventional Commits, runbook/onboarding e diagramas Mermaid. Registros append-only datados, derivados do git/cÃ³digo; nunca inventa. Use ao registrar o que mudou/aconteceu ou documentar como algo funciona.';
MERGE (n:Agent {name: 'explorer'}) SET n.role = 'search', n.description = 'Explora uma codebase desconhecida e devolve um mapa conciso (pontos de entrada, como conecta, onde a mudanÃ§a entra) sem despejar arquivos. Segue o call graph (definiÃ§Ã£oâ†’usosâ†’testes), nÃ£o sÃ³ hits de grep; domina ripgrep avanÃ§ado (tipos, contexto, -w, globs), ast-grep (busca por AST) e tags/LSP. Use para "onde fica X" antes de implementar. Read-only.';
MERGE (n:Agent {name: 'external-observer'}) SET n.role = 'observation', n.description = 'Observador de caixa-preta â€” valida ou mapeia um alvo externo/opaco (site, API, app rodando) por observaÃ§Ã£o read-only (rede/HAR, headers de cache/CDN, contrato/OpenAPI), separando fato de hipÃ³tese com evidÃªncia real e respeitando autorizaÃ§Ã£o (CFAA/ToS/robots). Confronta com uma referÃªncia; nunca replica, burla nem aplica. SaÃ­da: relatÃ³rio.';
MERGE (n:Agent {name: 'git-workflow'}) SET n.role = 'vcs', n.description = 'Expert em higiene de repositÃ³rio e fluxo Git/PR â€” Conventional Commits, commits atÃ´micos/bisect-friendly, rebase Ã— merge (regra de ouro do histÃ³rico compartilhado), .gitignore preciso, PRs pequenos e revisÃ¡veis. Conhece Git-Worktree (isolar branches/sessÃµes paralelas sem colidir na working tree) e aplica isso a outras Ã¡reas, como coordenaÃ§Ã£o de sessÃµes concorrentes (/peers). Use ao preparar commits/PRs, revisar histÃ³rico, organizar o repo ou paralelizar trabalho. Roda git/gh.';
MERGE (n:Agent {name: 'media-pipeline-specialist'}) SET n.role = 'review', n.description = 'Implementar ou revisar a camada que fala com yt-dlp/ffmpeg â€” seleÃ§Ã£o de formato, muxing vÃ­deo+Ã¡udio, extraÃ§Ã£o de Ã¡udio, parsing de progresso e taxonomia de erros do extractor. Acione ao mexer no nÃºcleo de download do youtube-downloader.';
MERGE (n:Agent {name: 'security-reviewer'}) SET n.role = 'security', n.description = 'RevisÃ£o de seguranÃ§a em profundidade (AppSec) guiada por fronteira de confianÃ§a â€” OWASP Top 10 (2021/2025) e ASVS, injeÃ§Ã£o/SSRF/desserializaÃ§Ã£o/IDOR, authn/authz, cripto, supply-chain (SLSA, lockfiles/pinning), segredos no working-tree e no histÃ³rico git (pickaxe, gitleaks/trufflehog) e audit de deps (osv-scanner/pip-audit/npm audit). Read-only.';
MERGE (n:Agent {name: 'test-writer'}) SET n.role = 'testing', n.description = 'Escreve/completa testes na stack do projeto cobrindo caminho feliz, bordas, falhas e os Acceptance Tests do DEFINE. Domina pirÃ¢mideÃ—trofÃ©u, AAA, testar contrato (nÃ£o implementaÃ§Ã£o), determinismo anti-flaky (relÃ³gio/RNG/ordem/estado/async), property-based (Hypothesis/fast-check), mutation testing (mutmut/Stryker) para provar que os testes matam bugs, e mock sem sobre-mock. LÃª o setup do projeto â€” nÃ£o inventa framework. Cria/edita testes e roda.';
MERGE (n:Agent {name: 'tracker'}) SET n.role = 'tracking', n.description = 'Expert em trÃ¡fego/traqueamento server-side. Domina sGTM (webâ†’tag mÃ£eâ†’servidor first-partyâ†’GA4/Meta CAPI/Google Ads), dedup clientÃ—server por `event_id`/`transaction_id`, click-ids (fbclidâ†’fbc, gclid/gbraid/wbraid) com fallback e ITP, PII normalizada+SHA-256 hex, Enhanced Conversions, atribuiÃ§Ã£o cross-domain, Consent Mode v2 (EEA) e QA de runtime (DebugView/Tag Assistant/Test Events/EMQ). LÃª o setup do projeto â€” nÃ£o carrega IDs/eventos fixos.';
MERGE (n:Agent {name: 'validator'}) SET n.role = 'validation', n.description = 'Verifica se o resultado entregue cumpre a spec e os Acceptance Tests do DEFINE â€” executa e observa o comportamento real, checa exit code (nÃ£o sÃ³ stdout), cobre o caso negativo e a fronteira, e isola o veredito em ambiente reprodutÃ­vel (worktree limpo, deps do zero). Distingue cumpre/parcial/nÃ£o-cumpre com evidÃªncia. NÃ£o conserta â€” sÃ³ verifica. Read-only.';
MERGE (n:Agent {name: 'ytdlp-simulator'}) SET n.role = 'simulation', n.description = 'Simular uma mudanÃ§a na seleÃ§Ã£o de formato do yt-dlp antes de aplicÃ¡-la â€” mostra o que SERIA baixado (formato, codec, tamanho, se precisa muxing) sem baixar byte nenhum. Acione a partir do /simulate ao mexer em seletor de formato, resoluÃ§Ã£o ou pÃ³s-processamento.';
MERGE (n:Domain {name: 'github-actions'}) SET n.role = '', n.description = '';
MERGE (n:Domain {name: 'media'}) SET n.role = '', n.description = '';
MERGE (n:Domain {name: 'node-packaging'}) SET n.role = '', n.description = '';
MERGE (n:Hub {name: 'max'}) SET n.role = 'orchestrator-hub', n.description = 'Modo MAX — hub orquestrador-mestre do grafo de agentes (H7)';
MERGE (n:KbEntry {name: 'autoatualizacao-do-binario'}) SET n.role = '', n.description = '', n.layer = 'tools', n.domain = 'media', n.contenttype = 'reference', n.status = 'active';
MERGE (n:KbEntry {name: 'saida-programatica'}) SET n.role = '', n.description = '', n.layer = 'tools', n.domain = 'media', n.contenttype = 'reference', n.status = 'active';
MERGE (n:KbEntry {name: 'selecao-de-formato'}) SET n.role = '', n.description = '', n.layer = 'tools', n.domain = 'media', n.contenttype = 'pattern', n.status = 'active';
MERGE (n:KbEntry {name: 'taxonomia-de-erros'}) SET n.role = '', n.description = '', n.layer = 'tools', n.domain = 'media', n.contenttype = 'reference', n.status = 'active';
MERGE (n:Skill {name: 'binary-size-budget'}) SET n.role = '', n.description = '', n.status = 'needed';
MERGE (n:Skill {name: 'decision-preview'}) SET n.role = '', n.description = '', n.scope = 'project', n.status = 'valid';
MERGE (n:Skill {name: 'gerador-de-manuais'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'impeccable'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'media-format-selection'}) SET n.role = '', n.description = '', n.status = 'needed';
MERGE (n:Skill {name: 'page-to-markdown'}) SET n.role = '', n.description = '', n.scope = 'project', n.status = 'valid';
MERGE (n:Skill {name: 'release-workflow'}) SET n.role = '', n.description = '', n.status = 'needed';
MERGE (n:Skill {name: 'security-guidance'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'ui-ux-pro-max'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'visual-explainer'}) SET n.role = '', n.description = '', n.status = 'referenced';
MATCH (a {name: 'autoatualizacao-do-binario'}), (b {name: 'media'}) MERGE (a)-[:IN_DOMAIN]->(b);
MATCH (a {name: 'autoatualizacao-do-binario'}), (b {name: 'saida-programatica'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'autoatualizacao-do-binario'}), (b {name: 'taxonomia-de-erros'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'build-release-specialist'}), (b {name: 'git-workflow'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'build-release-specialist'}), (b {name: 'media-pipeline-specialist'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'build-release-specialist'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'code-reviewer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'code-reviewer'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'designer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'designer'}), (b {name: 'impeccable'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'designer'}), (b {name: 'ui-ux-pro-max'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'designer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'gerador-de-manuais'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'visual-explainer'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'documenter'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'page-to-markdown'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'github-actions'}), (b {name: 'release-workflow'}) MERGE (a)-[:PRESUPPOSES]->(b);
MATCH (a {name: 'git-workflow'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'max'}), (b {name: 'build-release-specialist'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'code-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'debugger'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'designer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'documenter'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'explorer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'external-observer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'git-workflow'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'media-pipeline-specialist'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'security-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'test-writer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'tracker'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'validator'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'ytdlp-simulator'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'media'}), (b {name: 'media-format-selection'}) MERGE (a)-[:PRESUPPOSES]->(b);
MATCH (a {name: 'media-pipeline-specialist'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'media-pipeline-specialist'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'media-pipeline-specialist'}), (b {name: 'ytdlp-simulator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'node-packaging'}), (b {name: 'binary-size-budget'}) MERGE (a)-[:PRESUPPOSES]->(b);
MATCH (a {name: 'saida-programatica'}), (b {name: 'media'}) MERGE (a)-[:IN_DOMAIN]->(b);
MATCH (a {name: 'saida-programatica'}), (b {name: 'selecao-de-formato'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'saida-programatica'}), (b {name: 'taxonomia-de-erros'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'security-reviewer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'security-reviewer'}), (b {name: 'security-guidance'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'selecao-de-formato'}), (b {name: 'media'}) MERGE (a)-[:IN_DOMAIN]->(b);
MATCH (a {name: 'selecao-de-formato'}), (b {name: 'saida-programatica'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'selecao-de-formato'}), (b {name: 'taxonomia-de-erros'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'taxonomia-de-erros'}), (b {name: 'autoatualizacao-do-binario'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'taxonomia-de-erros'}), (b {name: 'media'}) MERGE (a)-[:IN_DOMAIN]->(b);
MATCH (a {name: 'taxonomia-de-erros'}), (b {name: 'saida-programatica'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'taxonomia-de-erros'}), (b {name: 'selecao-de-formato'}) MERGE (a)-[:RELATED_TO]->(b);
MATCH (a {name: 'test-writer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'external-observer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'validator'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'ytdlp-simulator'}), (b {name: 'media-pipeline-specialist'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'ytdlp-simulator'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);