CREATE CONSTRAINT node_agent_name IF NOT EXISTS FOR (n:Agent) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_hub_name IF NOT EXISTS FOR (n:Hub) REQUIRE n.name IS UNIQUE;
CREATE CONSTRAINT node_skill_name IF NOT EXISTS FOR (n:Skill) REQUIRE n.name IS UNIQUE;
MERGE (n:Agent {name: 'code-reviewer'}) SET n.role = 'review', n.description = 'Revisor sênior de diff/PR. Prioriza por risco (correção, concorrência, recursos, contrato/retrocompat, performance), lê o contexto e os chamadores além do diff, revisa o que ficou de fora e casa a linguagem com a severidade — sinal alto, sem nit-bombing. Delega estilo aos linters de CI e profundidade de segurança ao security-reviewer. Read-only.';
MERGE (n:Agent {name: 'debugger'}) SET n.role = 'debug', n.description = 'Vai da falha à causa-raiz pelo método científico (hipótese→predição→experimento→observação), não ao sintoma. Reproduz primeiro, checa ambiente antes da lógica, reduz o reprodutor (delta debugging), instrumenta com logs/traces, usa debugger e git bisect para regressão, e trata heisenbug/flaky/concorrência. Use quando algo quebra ou um teste falha sem causa óbvia.';
MERGE (n:Agent {name: 'designer'}) SET n.role = 'design', n.description = 'Expert em UI/frontend que conduz shape→craft→audit — contraste WCAG/APCA, design tokens (primitivo×semântico), tipografia/espaço fluido, ARIA APG, Core Web Vitals (CLS/LCP/INP), motion com prefers-reduced-motion, anti-slop, static-first. Use ao criar/revisar/refinar interface. Aponta para a skill `impeccable` quando instalada (`/supplements design`); sem ela, aplica a mesma disciplina diretamente. Não carrega paleta/referências fixas de nenhum projeto.';
MERGE (n:Agent {name: 'documenter'}) SET n.role = 'documentation', n.description = 'Expert em escrita técnica humano×LLM (fora da KB) — organiza `docs/` por Diátaxis (tutorial/how-to/reference/explanation), lavra ADR (Nygard/MADR), changelog Keep a Changelog derivado de Conventional Commits, runbook/onboarding e diagramas Mermaid. Registros append-only datados, derivados do git/código; nunca inventa. Use ao registrar o que mudou/aconteceu ou documentar como algo funciona.';
MERGE (n:Agent {name: 'explorer'}) SET n.role = 'search', n.description = 'Explora uma codebase desconhecida e devolve um mapa conciso (pontos de entrada, como conecta, onde a mudança entra) sem despejar arquivos. Segue o call graph (definição→usos→testes), não só hits de grep; domina ripgrep avançado (tipos, contexto, -w, globs), ast-grep (busca por AST) e tags/LSP. Use para "onde fica X" antes de implementar. Read-only.';
MERGE (n:Agent {name: 'external-observer'}) SET n.role = 'observation', n.description = 'Observador de caixa-preta — valida ou mapeia um alvo externo/opaco (site, API, app rodando) por observação read-only (rede/HAR, headers de cache/CDN, contrato/OpenAPI), separando fato de hipótese com evidência real e respeitando autorização (CFAA/ToS/robots). Confronta com uma referência; nunca replica, burla nem aplica. Saída: relatório.';
MERGE (n:Agent {name: 'git-workflow'}) SET n.role = 'vcs', n.description = 'Expert em higiene de repositório e fluxo Git/PR — Conventional Commits, commits atômicos/bisect-friendly, rebase × merge (regra de ouro do histórico compartilhado), .gitignore preciso, PRs pequenos e revisáveis. Conhece Git-Worktree (isolar branches/sessões paralelas sem colidir na working tree) e aplica isso a outras áreas, como coordenação de sessões concorrentes (/peers). Use ao preparar commits/PRs, revisar histórico, organizar o repo ou paralelizar trabalho. Roda git/gh.';
MERGE (n:Agent {name: 'security-reviewer'}) SET n.role = 'security', n.description = 'Revisão de segurança em profundidade (AppSec) guiada por fronteira de confiança — OWASP Top 10 (2021/2025) e ASVS, injeção/SSRF/desserialização/IDOR, authn/authz, cripto, supply-chain (SLSA, lockfiles/pinning), segredos no working-tree e no histórico git (pickaxe, gitleaks/trufflehog) e audit de deps (osv-scanner/pip-audit/npm audit). Read-only.';
MERGE (n:Agent {name: 'test-writer'}) SET n.role = 'testing', n.description = 'Escreve/completa testes na stack do projeto cobrindo caminho feliz, bordas, falhas e os Acceptance Tests do DEFINE. Domina pirâmide×troféu, AAA, testar contrato (não implementação), determinismo anti-flaky (relógio/RNG/ordem/estado/async), property-based (Hypothesis/fast-check), mutation testing (mutmut/Stryker) para provar que os testes matam bugs, e mock sem sobre-mock. Lê o setup do projeto — não inventa framework. Cria/edita testes e roda.';
MERGE (n:Agent {name: 'tracker'}) SET n.role = 'tracking', n.description = 'Expert em tráfego/traqueamento server-side. Domina sGTM (web→tag mãe→servidor first-party→GA4/Meta CAPI/Google Ads), dedup client×server por `event_id`/`transaction_id`, click-ids (fbclid→fbc, gclid/gbraid/wbraid) com fallback e ITP, PII normalizada+SHA-256 hex, Enhanced Conversions, atribuição cross-domain, Consent Mode v2 (EEA) e QA de runtime (DebugView/Tag Assistant/Test Events/EMQ). Lê o setup do projeto — não carrega IDs/eventos fixos.';
MERGE (n:Agent {name: 'validator'}) SET n.role = 'validation', n.description = 'Verifica se o resultado entregue cumpre a spec e os Acceptance Tests do DEFINE — executa e observa o comportamento real, checa exit code (não só stdout), cobre o caso negativo e a fronteira, e isola o veredito em ambiente reprodutível (worktree limpo, deps do zero). Distingue cumpre/parcial/não-cumpre com evidência. Não conserta — só verifica. Read-only.';
MERGE (n:Hub {name: 'max'}) SET n.role = 'orchestrator-hub', n.description = 'Modo MAX — hub orquestrador-mestre do grafo de agentes (H7)';
MERGE (n:Skill {name: 'decision-preview'}) SET n.role = '', n.description = '', n.scope = 'project', n.status = 'valid';
MERGE (n:Skill {name: 'gerador-de-manuais'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'impeccable'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'page-to-markdown'}) SET n.role = '', n.description = '', n.scope = 'project', n.status = 'valid';
MERGE (n:Skill {name: 'security-guidance'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'ui-ux-pro-max'}) SET n.role = '', n.description = '', n.status = 'referenced';
MERGE (n:Skill {name: 'visual-explainer'}) SET n.role = '', n.description = '', n.status = 'referenced';
MATCH (a {name: 'code-reviewer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'code-reviewer'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'debugger'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'designer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'designer'}), (b {name: 'impeccable'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'designer'}), (b {name: 'ui-ux-pro-max'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'designer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'explorer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'gerador-de-manuais'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'documenter'}), (b {name: 'visual-explainer'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'explorer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'debugger'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'documenter'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'page-to-markdown'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'external-observer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'git-workflow'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'max'}), (b {name: 'code-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'debugger'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'designer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'documenter'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'explorer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'external-observer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'git-workflow'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'security-reviewer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'test-writer'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'tracker'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'max'}), (b {name: 'validator'}) MERGE (a)-[:ORCHESTRATES]->(b);
MATCH (a {name: 'security-reviewer'}), (b {name: 'code-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'security-reviewer'}), (b {name: 'security-guidance'}) MERGE (a)-[:USES_SKILL]->(b);
MATCH (a {name: 'test-writer'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'external-observer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'security-reviewer'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'tracker'}), (b {name: 'validator'}) MERGE (a)-[:CONNECTS_TO]->(b);
MATCH (a {name: 'validator'}), (b {name: 'test-writer'}) MERGE (a)-[:CONNECTS_TO]->(b);